services:
  db:    
    image: mysql:5.7
    container_name: rachao-database
    restart: unless-stopped
    environment:      
      MYSQL_USER: "rachao"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      - "3306:3306"
    volumes:
      - .data:/var/lib/mysql
    networks:
      - app-network
  php:
    user: 1000:1000
    build:
      args:
        user: teste
        uid: 1000
      context: .docker/php
      dockerfile: Dockerfile  
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - .docker/apache/sites-available:/etc/apache2/sites-enabled
    depends_on:
      - db
    networks:
      - app-network  
networks:
  app-network:
    name: app-network
    driver: bridge
